FROM node:20-alpine as builder
WORKDIR /app

COPY . .

RUN yarn install

WORKDIR /app/hospital-lib
RUN yarn install
RUN yarn build:prod

WORKDIR /app/hospital-fe
RUN yarn install
RUN yarn build

FROM nginx:alpine
COPY --from=builder /app/hospital-fe/dist/hospital-fe/browser /app/frontend/browser
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]